/**
 * Generates the event bus client — a thin abstraction over the underlying
 * transport (AMQP for RabbitMQ, SNS for AWS). The client provides connect,
 * publish, and subscribe functions that publishers and subscribers import.
 */
export function generateClient(engine: string): string {
  return `// ── Event Bus Client ───────────────────────────────────────────────────────
// Auto-generated by event-bus-cell. Do not edit.
// Engine: ${engine}

const EVENT_BUS_URL = process.env.EVENT_BUS_URL || 'amqp://localhost:5672'

type MessageHandler = (signal: string, payload: unknown) => Promise<void>

let connection: unknown = null

export async function connect(): Promise<void> {
  // Placeholder — adapter-specific transport initialization.
  // RabbitMQ: amqplib connection + channel
  // AWS: SNS/SQS client initialization
  console.log(\`[event-bus] Connecting to \${EVENT_BUS_URL}...\`)
  connection = { url: EVENT_BUS_URL, connected: true }
  console.log('[event-bus] Connected.')
}

export async function disconnect(): Promise<void> {
  connection = null
  console.log('[event-bus] Disconnected.')
}

export async function publish(signal: string, payload: unknown): Promise<void> {
  if (!connection) {
    throw new Error('[event-bus] Not connected. Call connect() first.')
  }
  const message = JSON.stringify({ signal, payload, timestamp: new Date().toISOString() })
  console.log(\`[event-bus] Publishing \${signal}: \${message}\`)
  // Placeholder — adapter-specific publish.
  // RabbitMQ: channel.publish(exchange, routingKey, Buffer.from(message))
  // AWS: sns.publish({ TopicArn, Message: message })
}

export async function subscribe(signal: string, handler: MessageHandler): Promise<void> {
  if (!connection) {
    throw new Error('[event-bus] Not connected. Call connect() first.')
  }
  console.log(\`[event-bus] Subscribing to \${signal}\`)
  // Placeholder — adapter-specific subscribe.
  // RabbitMQ: channel.consume(queue, msg => handler(signal, JSON.parse(msg.content)))
  // AWS: SQS polling loop
}
`
}
