/**
 * Generates the event bus client — a thin abstraction over the underlying
 * transport (AMQP for RabbitMQ, SNS for AWS). The client provides connect,
 * publish, and subscribe functions that publishers and subscribers import.
 */
export function generateClient(engine: string): string {
  if (engine === 'rabbitmq') return generateRabbitMQClient()
  if (engine === 'eventbridge') return generateEventBridgeClient()
  return generatePlaceholderClient(engine)
}

function generateRabbitMQClient(): string {
  return `// ── Event Bus Client ───────────────────────────────────────────────────────
// Auto-generated by event-bus-cell. Do not edit.
// Engine: rabbitmq

const amqp = require('amqplib') as typeof import('amqplib')

const EVENT_BUS_URL = process.env.EVENT_BUS_URL || 'amqp://localhost:5672'
const EXCHANGE = 'signals'

type MessageHandler = (signal: string, payload: unknown) => Promise<void>

let connection: any = null
let channel: any = null

export async function connect(): Promise<void> {
  console.log(\`[event-bus] Connecting to \${EVENT_BUS_URL}...\`)
  connection = await amqp.connect(EVENT_BUS_URL)
  channel = await connection.createChannel()
  await channel.assertExchange(EXCHANGE, 'topic', { durable: true })
  console.log('[event-bus] Connected.')
}

export async function disconnect(): Promise<void> {
  if (channel) { await channel.close(); channel = null }
  if (connection) { await connection.close(); connection = null }
  console.log('[event-bus] Disconnected.')
}

export async function publish(signal: string, payload: unknown): Promise<void> {
  if (!channel) throw new Error('[event-bus] Not connected. Call connect() first.')
  const message = JSON.stringify({ signal, payload, timestamp: new Date().toISOString() })
  channel.publish(EXCHANGE, signal, Buffer.from(message), { persistent: true })
  console.log(\`[event-bus] Published \${signal}\`)
}

export async function subscribe(signal: string, handler: MessageHandler): Promise<void> {
  if (!channel) throw new Error('[event-bus] Not connected. Call connect() first.')
  const queue = signal.replace(/\\./g, '-')
  await channel.assertQueue(queue, { durable: true })
  await channel.bindQueue(queue, EXCHANGE, signal)
  console.log(\`[event-bus] Subscribed to \${signal} via queue \${queue}\`)
  channel.consume(queue, async (msg: any) => {
    if (!msg) return
    try {
      const parsed = JSON.parse(msg.content.toString())
      await handler(parsed.signal, parsed.payload)
      channel!.ack(msg)
    } catch (err) {
      console.error(\`[event-bus] Handler error for \${signal}:\`, err)
      channel!.nack(msg, false, false)
    }
  })
}
`
}

function generateEventBridgeClient(): string {
  return `// ── Event Bus Client ───────────────────────────────────────────────────────
// Auto-generated by event-bus-cell. Do not edit.
// Engine: eventbridge (AWS EventBridge → SQS)

import { EventBridgeClient, PutEventsCommand } from '@aws-sdk/client-eventbridge'
import { SQSClient, ReceiveMessageCommand, DeleteMessageCommand } from '@aws-sdk/client-sqs'

const EVENT_BUS_NAME = process.env.EVENT_BUS_NAME || 'default'
const EVENT_BUS_QUEUE_URL = process.env.EVENT_BUS_QUEUE_URL || ''
const EVENT_BUS_SOURCE = process.env.EVENT_BUS_SOURCE || 'app'

type MessageHandler = (signal: string, payload: unknown) => Promise<void>

let ebClient: EventBridgeClient | null = null
let sqsClient: SQSClient | null = null
let polling = false

export async function connect(): Promise<void> {
  console.log(\`[event-bus] Connecting to EventBridge bus "\${EVENT_BUS_NAME}"...\`)
  ebClient = new EventBridgeClient({})
  sqsClient = new SQSClient({})
  polling = true
  console.log('[event-bus] Connected.')
}

export async function disconnect(): Promise<void> {
  polling = false
  if (ebClient) { ebClient.destroy(); ebClient = null }
  if (sqsClient) { sqsClient.destroy(); sqsClient = null }
  console.log('[event-bus] Disconnected.')
}

export async function publish(signal: string, payload: unknown): Promise<void> {
  if (!ebClient) throw new Error('[event-bus] Not connected. Call connect() first.')
  const detail = JSON.stringify({ signal, payload, timestamp: new Date().toISOString() })
  await ebClient.send(new PutEventsCommand({
    Entries: [{
      Source: EVENT_BUS_SOURCE,
      DetailType: signal,
      Detail: detail,
      EventBusName: EVENT_BUS_NAME,
    }],
  }))
  console.log(\`[event-bus] Published \${signal}\`)
}

export async function subscribe(signal: string, handler: MessageHandler): Promise<void> {
  if (!sqsClient || !EVENT_BUS_QUEUE_URL) {
    throw new Error('[event-bus] Not connected or EVENT_BUS_QUEUE_URL not set.')
  }
  console.log(\`[event-bus] Subscribed to \${signal} via SQS queue\`)

  // Long-poll loop — runs until disconnect() sets polling = false
  ;(async () => {
    while (polling) {
      try {
        const resp = await sqsClient!.send(new ReceiveMessageCommand({
          QueueUrl: EVENT_BUS_QUEUE_URL,
          MaxNumberOfMessages: 10,
          WaitTimeSeconds: 20,
        }))
        for (const msg of resp.Messages ?? []) {
          try {
            const envelope = JSON.parse(msg.Body ?? '{}')
            // EventBridge wraps events — unwrap the detail
            const detail = typeof envelope.detail === 'string'
              ? JSON.parse(envelope.detail)
              : envelope.detail ?? envelope
            if (detail.signal === signal) {
              await handler(detail.signal, detail.payload)
            }
            await sqsClient!.send(new DeleteMessageCommand({
              QueueUrl: EVENT_BUS_QUEUE_URL,
              ReceiptHandle: msg.ReceiptHandle!,
            }))
          } catch (err) {
            console.error(\`[event-bus] Handler error for \${signal}:\`, err)
            // Message stays in queue — returns after visibility timeout
          }
        }
      } catch (err) {
        if (polling) console.error('[event-bus] Poll error:', err)
      }
    }
  })()
}
`
}

function generatePlaceholderClient(engine: string): string {
  return `// ── Event Bus Client ───────────────────────────────────────────────────────
// Auto-generated by event-bus-cell. Do not edit.
// Engine: ${engine} (placeholder — implement transport adapter)

const EVENT_BUS_URL = process.env.EVENT_BUS_URL || ''

type MessageHandler = (signal: string, payload: unknown) => Promise<void>

export async function connect(): Promise<void> {
  console.log(\`[event-bus] Connecting to \${EVENT_BUS_URL}...\`)
}

export async function disconnect(): Promise<void> {
  console.log('[event-bus] Disconnected.')
}

export async function publish(signal: string, payload: unknown): Promise<void> {
  const message = JSON.stringify({ signal, payload, timestamp: new Date().toISOString() })
  console.log(\`[event-bus] Publishing \${signal}: \${message}\`)
}

export async function subscribe(signal: string, handler: MessageHandler): Promise<void> {
  console.log(\`[event-bus] Subscribing to \${signal}\`)
}
`
}
