import { Signal, PayloadField } from '../../../../types'

function tsType(field: PayloadField): string {
  switch (field.type) {
    case 'number': return 'number'
    case 'boolean': return 'boolean'
    case 'date':
    case 'datetime': return 'string'
    default: return 'string'
  }
}

function toPascalCase(s: string): string {
  return s.replace(/(?:^|[._-])(\w)/g, (_, c) => c.toUpperCase())
}

/**
 * Generates typed publisher functions — one per Signal.
 * Each function accepts a typed payload and publishes to the event bus.
 */
export function generatePublishers(signals: Signal[]): string {
  const interfaces: string[] = []
  const functions: string[] = []

  for (const signal of signals) {
    const typeName = toPascalCase(signal.name.split('.').slice(-2).join('.')) + 'Payload'
    const fields = signal.payload.map(f =>
      `  ${f.name}: ${tsType(f)}${f.description ? ` // ${f.description}` : ''}`
    ).join('\n')

    interfaces.push(`export interface ${typeName} {\n${fields}\n}`)

    const fnName = 'publish' + toPascalCase(signal.name.split('.').slice(-2).join('.'))
    functions.push(`export async function ${fnName}(payload: ${typeName}): Promise<void> {
  await publish('${signal.name}', payload)
}`)
  }

  return `// ── Typed Signal Publishers ────────────────────────────────────────────────
// Auto-generated by event-bus-cell. Do not edit.

import { publish } from './client'

${interfaces.join('\n\n')}

${functions.join('\n\n')}
`
}
