import { Signal, Cause } from '../../../../types'

interface RouteEntry {
  signal: string
  subscribers: { capability: string; description?: string }[]
}

/**
 * Generates the routing configuration — maps each Signal to the Capabilities
 * that subscribe to it (via Cause with source: "signal").
 */
export function generateRouting(signals: Signal[], causes: Cause[]): string {
  const signalCauses = causes.filter(c => c.source === 'signal' && c.signal)

  const routes: RouteEntry[] = signals.map(signal => ({
    signal: signal.name,
    subscribers: signalCauses
      .filter(c => c.signal === signal.name)
      .map(c => ({ capability: c.capability, description: c.description })),
  }))

  const entries = routes.map(route => {
    const subs = route.subscribers.map(s =>
      `      { capability: '${s.capability}'${s.description ? `, description: '${s.description.replace(/'/g, "\\'")}' ` : ''} }`
    ).join(',\n')
    return `  '${route.signal}': {
    subscribers: [
${subs}
    ],
  }`
  })

  return `// ── Signal Routing Configuration ───────────────────────────────────────────
// Auto-generated by event-bus-cell. Do not edit.

export interface Subscriber {
  capability: string
  description?: string
}

export interface SignalRoute {
  subscribers: Subscriber[]
}

export const SIGNAL_ROUTES: Record<string, SignalRoute> = {
${entries.join(',\n')}
}
`
}
