import { Signal } from '../../../../types'

/**
 * Generates a compiled catalog of all Signals across all domains with typed payloads.
 * Used at runtime by publishers and subscribers for payload validation.
 */
export function generateSchemaRegistry(signals: Signal[]): string {
  const entries = signals.map(signal => {
    const fields = signal.payload.map(f =>
      `      { name: '${f.name}', type: '${f.type}'${f.description ? `, description: '${f.description.replace(/'/g, "\\'")}' ` : ''} }`
    ).join(',\n')

    return `  '${signal.name}': {
    capability: '${signal.capability}',
    description: '${(signal.description ?? '').replace(/'/g, "\\'")}',
    payload: [
${fields}
    ],
  }`
  })

  return `// ── Signal Schema Registry ─────────────────────────────────────────────────
// Auto-generated by event-bus-cell. Do not edit.

export interface PayloadField {
  name: string
  type: 'string' | 'text' | 'number' | 'boolean' | 'date' | 'datetime'
  description?: string
}

export interface SignalSchema {
  capability: string
  description: string
  payload: PayloadField[]
}

export const SIGNAL_REGISTRY: Record<string, SignalSchema> = {
${entries.join(',\n')}
}

export const SIGNAL_NAMES = [${signals.map(s => `'${s.name}'`).join(', ')}] as const
export type SignalName = typeof SIGNAL_NAMES[number]
`
}
