import { Signal, Cause } from '../../../../types'

function toPascalCase(s: string): string {
  return s.replace(/(?:^|[._-])(\w)/g, (_, c) => c.toUpperCase())
}

function toCamelCase(s: string): string {
  const pascal = toPascalCase(s)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

/**
 * Generates skeleton subscriber/worker code. Each subscriber listens for a
 * Signal and invokes the corresponding Capability handler.
 */
export function generateSubscriberWorker(signals: Signal[], causes: Cause[]): string {
  const signalCauses = causes.filter(c => c.source === 'signal' && c.signal)

  const handlers = signalCauses.map(cause => {
    const signal = signals.find(s => s.name === cause.signal)
    if (!signal) return ''

    const typeName = toPascalCase(signal.name.split('.').slice(-2).join('.')) + 'Payload'
    const fnName = 'handle' + toPascalCase(cause.capability.replace('.', ''))

    return `async function ${fnName}(payload: ${typeName}): Promise<void> {
  // TODO: Implement ${cause.capability} handler
  // Triggered by signal: ${signal.name}
  console.log('[subscriber] ${cause.capability} triggered by ${signal.name}', payload)
}`
  }).filter(Boolean)

  const registrations = signalCauses.map(cause => {
    const fnName = 'handle' + toPascalCase(cause.capability.replace('.', ''))
    return `  await subscribe('${cause.signal}', async (_signal, payload) => {
    await ${fnName}(payload as any)
  })`
  })

  const imports = new Set<string>()
  for (const cause of signalCauses) {
    const signal = signals.find(s => s.name === cause.signal)
    if (signal) {
      imports.add(toPascalCase(signal.name.split('.').slice(-2).join('.')) + 'Payload')
    }
  }

  return `// ── Subscriber Worker ──────────────────────────────────────────────────────
// Auto-generated by event-bus-cell. Do not edit.
// Skeleton handlers — implement the TODO blocks with domain logic.

import { connect, disconnect, subscribe } from './client'
${imports.size > 0 ? `import type { ${[...imports].join(', ')} } from './publishers'\n` : ''}
${handlers.join('\n\n')}

export async function startSubscribers(): Promise<void> {
  await connect()
${registrations.join('\n')}
  console.log('[subscriber] All subscribers registered.')
}

// Entry point — run as a standalone worker
if (require.main === module) {
  startSubscribers().catch(err => {
    console.error('[subscriber] Fatal error:', err)
    process.exit(1)
  })
}
`
}
