import { DbAdapterConfig } from '../../../types'

export function generateEnv(config: DbAdapterConfig): string {
  // Superuser connection — for admin tasks like psql shells. The app connects
  // as app_role via drizzle migrations (owned by api-cell, not db-cell).
  const port = config.port ?? 5433
  return `DATABASE_URL=postgresql://postgres:postgres@localhost:${port}/${config.database}
`
}

export function generateReadme(config: DbAdapterConfig): string {
  const database = config.database
  const role = config.app_role ?? `${database}_app`
  const port = config.port ?? 5433

  return `# ${database}-db

Generated by db-cell (postgres adapter) — provisions a Postgres instance with
the \`${database}\` database and the \`${role}\` application role.

This cell is **infrastructure-only**: it does not own application tables.
Schema migrations, seeds, and queries are owned by api-cell via drizzle,
connecting as \`${role}\`.

## Run standalone

\`\`\`bash
docker compose up -d
# postgres is now available at localhost:${port}
# superuser: postgres / postgres
# app role:  ${role} / ${role}
\`\`\`

## What's in the image

- \`docker-compose.yml\` — postgres service with init scripts mounted
- \`docker/scripts/init.sql\` — creates the \`${role}\` role and grants privileges
- \`.env\` — superuser DATABASE_URL for local psql sessions

## Regenerating

Regenerated by \`cba develop <domain> --cell db-cell\`. Do not edit by hand —
edit the Technical DNA (\`Construct\`, Cell adapter config) instead.
`
}
